spring.application.name=EmployeeInvoice

spring.datasource.url=jdbc:mysql:///employeeinvoice?cloudSqlInstance=employeeinvoice:us-central1:employe-mysql&socketFactory=com.google.cloud.sql.mysql.SocketFactory

spring.datasource.username=root
spring.datasource.password=Yogiadithya@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}