spring.application.name=EmployeeInvoice

server.port=8080

# Google Cloud SQL MySQL Connection
spring.datasource.url=jdbc:mysql://google/dbproject?cloudSqlInstance=employeeinvoice:asia-south1:employee&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false

spring.datasource.username=employees
spring.datasource.password=Employee@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000